Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Todo.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Todo.Model;
using Todo.Repository;


namespace Todo.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ITodoRepo _todoRepo;
        private readonly ILogger<IndexModel> _logger;
        public List<Todos> todos { get; set; }

        [BindProperty]
        [MaxLength(25), Required]
        public string Description { get; set; }
        [BindProperty]
        public bool IsCompleted { get; set; }

        [BindProperty]
        public Todos todo { get; set; }

        public IndexModel(ITodoRepo repo, ILogger<IndexModel> logger)
        {
            _todoRepo = repo;
            todos = _todoRepo.GetTodo();

            _logger = logger;
        }

        public void OnGet()
        {
            
            
        }

        public void OnPost()
        {

        }
        
        public IActionResult OnPostEdit(Guid id, string UpdateDescription, bool UpdateCompleted)
        {
            _logger.LogWarning(id.ToString());
            Todos updateTodo = _todoRepo.GetItemById(id);
            updateTodo.TaskDescription = UpdateDescription;
            updateTodo.IsCompleted = UpdateCompleted;
            _todoRepo.UpdateTodo(updateTodo);
            return Page();
        }

        public void OnPostDelete(Guid id)
        {

            _todoRepo.DeleteTodo(id);
            
        }
        
        public void OnPostCreate()
        {
            _todoRepo.CreateTodo(new Todos() { Id = Guid.NewGuid(), TaskDescription = Description });
            
        }

        public IActionResult OnGetJsonObj(Guid id)
        {
            Todos todo = _todoRepo.GetItemById(id);
            return new JsonResult(todo);
        }

    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Todo.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<body class="text-center">

    <form method="post">
        <table class="table table-dark table-bordered">
            <tr>
                <th>ID</th>
                <th>Description</th>
                <th>Priority</th>
                <th>Created At</th>
                <th>Completed</th>
                <th><button type="button" class="btn btn-success" data-toggle="modal" data-target="#CreateTodo">Create todo</button></th>
                <th><button class="btn btn-light">Save table</button></th>
            </tr>


            @foreach (Model.Todos item in Model.todos)
            {
                @if (item.IsCompleted == false)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.TaskDescription</td>
                        <td>@item.Prio</td>
                        <td>@item.CreatedTime.ToString("MM-dd-yyyy")</td>
                        <td> <input type="checkbox" name="IsChecked" id="Completed" value="" /> </td>
                        <td><button type="button" id="@item.Id" data-toggle="modal" data-target="#UpdateModal" class="btn btn-warning btnUpdate">Edit</button></td>
                        <td><button type="submit" asp-page-handler="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</button></td>
                    </tr>


                }
            }
        </table>
    </form>


    <!-- Modal for Create-->
    <div class="modal fade" id="CreateTodo" tabindex="-1" role="dialog" aria-labelledby="ModalCreateTodo" aria-hidden="true">
        <div asp-validation-summary="ModelOnly"></div>
        <form method="post" enctype="multipart/form-data">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Create Todo</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body flex">
                        @*<div class="w-25 text-left">
                                <input type="radio" name="prio" value="Low" />Low <br />
                                <input type="radio" name="prio" value="Normal" checked/>Normal <br />
                                <input type="radio" name="prio" value="High" />High <br />
                            </div>*@
                        <div class="w-75">
                            <p>Write description of the todo:</p>
                            <input type="text" asp-for="Description" name="Description" value="" style="width:75%;" /><br />
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <input class="btn btn-primary" type="submit" name="name" value="Create Todo" asp-page-handler="Create" />
                    </div>
                </div>
            </div>
        </form>
    </div>

    <!-- Modal for update-->
    <div class="modal fade" id="UpdateModal" tabindex="-1" role="dialog" aria-labelledby="ModalUpdateTodo" aria-hidden="true">
        <form method="post">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Update Todo</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body flex">
                        @*<div class="w-25 text-left">
                                <input type="radio" name="prio" value="Low" />Low <br />
                                <input type="radio" name="prio" value="Normal" checked/>Normal <br />
                                <input type="radio" name="prio" value="High" />High <br />
                            </div>*@
                        <div class="w-75">
                            <p>Write new description of the todo:</p>
                            <input type="text" id="Description" asp-for="Description" name="UpdateDescription" value="" style="width:75%;" /><br />
                            <span asp-validation-for="Description" class="text-danger"></span>
                            <input type="hidden" name="id" id="id" value="" />
                            <input type="checkbox" name="UpdateCompleted" id="IsCompleted" value="true" asp-for="IsCompleted"/>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <input class="btn btn-primary" type="submit" name="name" value="Update Todo" asp-page-handler="Edit" />
                    </div>
                </div>
            </div>
        </form>
    </div>



</body>
@section scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
$(function () {
    $('button.btnUpdate').on('click', function () {
        var id = $(this).attr('id');
            $.ajax({
                type: "GET",
                data: {id:id},
                url: '@Url.Page("Index", "JsonObj")',
                success: function (result) {
                        console.log(result);
                    $('#UpdateModal #id').val(result.id)
                    $('#UpdateModal #Description').val(result.taskDescription)
                    $('#UpdateModal #IsCompleted').val(result.isCompleted)
                }
            });
        });
    });
    </script>
}

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Todo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Todo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Todo - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>